import os
import shutil
from PIL import Image, ImageFilter

brain_dir = r"C:\Users\a\.gemini\antigravity-ide\brain\5f8ce7c0-80ea-41f0-881a-37a78d8dac62"
target_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'public', 'images', 'hero'))
os.makedirs(target_dir, exist_ok=True)

images = {
    'la': 'la_hero_1791098488370.jpg',
    'nj': 'nj_hero_1791098509906.jpg',
    'ma': 'ma_hero_1791098535216.jpg'
}

attribution_lines = ["# Image Attribution\n\nAll images were generated by Antigravity AI.\n"]

for name, filename in images.items():
    src_path = os.path.join(brain_dir, filename)
    print(f"Processing {name} from {src_path}")
    
    if not os.path.exists(src_path):
        raise Exception(f"File not found: {src_path}")
        
    try:
        with Image.open(src_path) as img:
            img = img.convert('RGB')
            # Save original JPG
            jpg_path = os.path.join(target_dir, f"{name}.jpg")
            img.save(jpg_path, 'JPEG', quality=85)
            
            # Save WebP
            webp_path = os.path.join(target_dir, f"{name}.webp")
            img.save(webp_path, 'WEBP', quality=85)
            
            # Save blur placeholder
            blur_path = os.path.join(target_dir, f"{name}_blur.jpg")
            img.resize((20, int(20 * img.height / img.width))).filter(ImageFilter.GaussianBlur(2)).save(blur_path, 'JPEG', quality=50)
            
    except Exception as e:
        raise Exception(f"Failed to process {name}: {e}")
        
    attribution_lines.append(f"- **{name.upper()}**: Generated by Antigravity AI.\n")

with open(os.path.join(target_dir, 'ATTRIBUTION.md'), 'w', encoding='utf-8') as f:
    f.writelines(attribution_lines)

print("Images copied and processed successfully!")
